version: 1.2.{build}
branches:
  only:
  - develop
image: Visual Studio 2017
clone_depth: 1
before_build:
- ps: >-
    cd src

    dotnet restore
build:
  project: src\Hl7.Fhir.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - e.kramer@furore.com
  subject: AppVeyor Build Report (DSTU2 .NET Core)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false